var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
""(__makeTemplateObject(["typescript\n/**\n * CodeLine - AI Coding Assistant\n * Main application entry point\n */\n\nimport { CodeLineApp } from \"./app/CodeLineApp\";\nimport { Logger } from \"./utils/Logger\";\n\n/**\n * Main application class\n */\nclass Main {\n    private app: CodeLineApp;\n    private logger: Logger;\n\n    constructor() {\n        this.logger = Logger.getInstance();\n        this.app = new CodeLineApp();\n    }\n\n    /**\n     * Initialize and start the application\n     */\n    public async start(): Promise<void> {\n        try {\n            this.logger.info(\"Starting CodeLine application...\");\n            \n            // Initialize the application\n            await this.app.initialize();\n            \n            // Start the application\n            await this.app.start();\n            \n            this.logger.info(\"CodeLine application started successfully\");\n            \n            // Handle graceful shutdown\n            this.setupShutdownHandlers();\n            \n        } catch (error) {\n            this.logger.error(\"Failed to start application:\", error);\n            process.exit(1);\n        }\n    }\n\n    /**\n     * Setup shutdown handlers for graceful termination\n     */\n    private setupShutdownHandlers(): void {\n        const signals: NodeJS.Signals[] = [\"SIGINT\", \"SIGTERM\", \"SIGQUIT\"];\n        \n        signals.forEach(signal => {\n            process.on(signal, async () => {\n                this.logger.info("], ["typescript\n/**\n * CodeLine - AI Coding Assistant\n * Main application entry point\n */\n\nimport { CodeLineApp } from \"./app/CodeLineApp\";\nimport { Logger } from \"./utils/Logger\";\n\n/**\n * Main application class\n */\nclass Main {\n    private app: CodeLineApp;\n    private logger: Logger;\n\n    constructor() {\n        this.logger = Logger.getInstance();\n        this.app = new CodeLineApp();\n    }\n\n    /**\n     * Initialize and start the application\n     */\n    public async start(): Promise<void> {\n        try {\n            this.logger.info(\"Starting CodeLine application...\");\n            \n            // Initialize the application\n            await this.app.initialize();\n            \n            // Start the application\n            await this.app.start();\n            \n            this.logger.info(\"CodeLine application started successfully\");\n            \n            // Handle graceful shutdown\n            this.setupShutdownHandlers();\n            \n        } catch (error) {\n            this.logger.error(\"Failed to start application:\", error);\n            process.exit(1);\n        }\n    }\n\n    /**\n     * Setup shutdown handlers for graceful termination\n     */\n    private setupShutdownHandlers(): void {\n        const signals: NodeJS.Signals[] = [\"SIGINT\", \"SIGTERM\", \"SIGQUIT\"];\n        \n        signals.forEach(signal => {\n            process.on(signal, async () => {\n                this.logger.info("]));
Received;
$;
{
    signal;
}
shutting;
down;
gracefully;
");\n                try {\n                    await this.app.shutdown();\n                    this.logger.info(\"Application shutdown complete\");\n                    process.exit(0);\n                } catch (error) {\n                    this.logger.error(\"Error during shutdown:\", error);\n                    process.exit(1);\n                }\n            });\n        });\n\n        // Handle uncaught exceptions\n        process.on(\"uncaughtException\", (error: Error) => {\n            this.logger.error(\"Uncaught exception:\", error);\n            process.exit(1);\n        });\n\n        // Handle unhandled promise rejections\n        process.on(\"unhandledRejection\", (reason: unknown) => {\n            this.logger.error(\"Unhandled promise rejection:\", reason);\n            process.exit(1);\n        });\n    }\n}\n\n// Start the application\nif (require.main === module) {\n    const main = new Main();\n    main.start().catch(error => {\n        console.error(\"Fatal error during application startup:\", error);\n        process.exit(1);\n    });\n}\n\nexport { Main };\n"(__makeTemplateObject([""], [""]));
